// ============================================================================
// sincos_lut.sv
//
//  Quarter-wave sin/cos lookup with linear interpolation.
//
//  - One RAMB36 (1024 x 36, true dual port): word = {val Q1.17, slope},
//    table generated by scripts/gen_sincos_lut.py (sincos_lut.mem).
//  - Angle: unsigned 16 bit, full circle = 2^16 codes.
//    Quadrant folding: quad = theta[15:14], phase p = theta[13:0];
//    odd quadrants mirror (c = 16384 - p), quad MSB gives the sign.
//    c == 16384 (exact peak) bypasses the table and returns +/- full scale.
//  - Interpolation: y = val + slope * frac/16, frac = c[3:0]; total error
//    vs. double precision sin is < 1 LSB of Q1.15.
//  - cos(theta) = sin(theta + 0x4000): the second BRAM port serves cos.
//  - Latency: 3 clk cycles (BRAM read, interpolate, round/sign - the
//    interpolation multiply gets its own stage to meet 100 MHz); in_valid
//    is piped to out_valid. Inputs may stream back to back.
// ============================================================================

module sincos_lut
  import foc_pkg::*;
#(
  parameter string MEM_FILE = "sincos_lut.mem",
  parameter int unsigned LATENCY = 3 // informational, fixed by the pipeline
)(
  input  logic   clk,
  input  logic   rst_n,
  input  logic   in_valid,
  input  angle_t theta,
  output logic   out_valid,
  output q15_t   sin_o,
  output q15_t   cos_o
);

  // ------------------------------------------------------------------
  // Quarter-wave table: {val[17:0], slope[17:0]}
  // ------------------------------------------------------------------
  logic [35:0] mem [0:1023];
  initial $readmemh(MEM_FILE, mem);

  typedef struct packed {
    logic       sign;  // quadrant 2/3 -> negate
    logic       top;   // c == 16384 -> exact peak, bypass table
    logic [9:0] addr;
    logic [3:0] frac;
  } lut_ctl_t;

  function automatic lut_ctl_t decode(input angle_t a);
    logic [14:0] c;
    lut_ctl_t    r;
    if (a[14]) c = 15'd16384 - 15'(a[13:0]); // mirrored quadrant
    else       c = 15'(a[13:0]);
    r.sign = a[15];
    r.top  = (c == 15'd16384);
    r.addr = c[13:4];
    r.frac = c[3:0];
    return r;
  endfunction

  // ------------------------------------------------------------------
  // Stage 0 (comb): address decode for sin and cos channels
  // ------------------------------------------------------------------
  lut_ctl_t s_ctl_d, c_ctl_d;
  assign s_ctl_d = decode(theta);
  assign c_ctl_d = decode(angle_t'(theta + 16'h4000)); // cos = sin shifted

  // ------------------------------------------------------------------
  // Stage 1: synchronous dual-port BRAM read + control pipe
  // ------------------------------------------------------------------
  logic [35:0] s_word, c_word;
  lut_ctl_t    s_ctl_q, c_ctl_q;
  logic        v1;

  always_ff @(posedge clk) begin
    s_word  <= mem[s_ctl_d.addr];
    c_word  <= mem[c_ctl_d.addr];
    s_ctl_q <= s_ctl_d;
    c_ctl_q <= c_ctl_d;
  end

  // ------------------------------------------------------------------
  // Stage 2: interpolate to Q1.17 (multiply + add), registered
  // ------------------------------------------------------------------
  function automatic logic [18:0] interp17(input logic [35:0] w,
                                           input lut_ctl_t ctl);
    logic [17:0] val, slope;
    val   = w[35:18];
    slope = w[17:0];
    return 19'(val) + 19'((22'(slope) * 22'(ctl.frac) + 22'd8) >> 4);
  endfunction

  logic [18:0] s_y17, c_y17;
  logic        s_top, c_top, s_sign, c_sign;

  always_ff @(posedge clk) begin
    s_y17  <= interp17(s_word, s_ctl_q);
    c_y17  <= interp17(c_word, c_ctl_q);
    s_top  <= s_ctl_q.top;   c_top  <= c_ctl_q.top;
    s_sign <= s_ctl_q.sign;  c_sign <= c_ctl_q.sign;
  end

  // ------------------------------------------------------------------
  // Stage 3: round Q1.17 -> Q1.15, saturate, apply sign
  // ------------------------------------------------------------------
  function automatic q15_t finish15(input logic [18:0] y17,
                                    input logic top, input logic sign);
    logic [16:0] m15;
    logic [15:0] mag;
    if (top) mag = 16'd32767;
    else begin
      m15 = 17'((y17 + 19'd2) >> 2);
      mag = (m15 > 17'd32767) ? 16'd32767 : 16'(m15);
    end
    return sign ? q15_t'(-mag) : q15_t'(mag);
  endfunction

  always_ff @(posedge clk) begin
    sin_o <= finish15(s_y17, s_top, s_sign);
    cos_o <= finish15(c_y17, c_top, c_sign);
  end

  logic v2;
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      v1        <= 1'b0;
      v2        <= 1'b0;
      out_valid <= 1'b0;
    end else begin
      v1        <= in_valid;
      v2        <= v1;
      out_valid <= v2;
    end
  end

endmodule
